version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=fidex
      - DB_USERNAME=postgres
      - DB_PASSWORD=Deo
    image: docker-deo-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/
    depends_on:
      - postgres
    networks:
      - fidex

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: fidex
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Deo
    ports:
      - "5432:5432"
    networks:
      - fidex
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: deoclecio.steinheuser@gmail.com
      PGADMIN_DEFAULT_PASSWORD: deo
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - fidex

networks:
  fidex:
volumes:
  postgres_data:
