version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    image: docker-deo-app
    ports:
      - "8080:80"
    volumes:
      - .:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
